parameters:
    twig.extension.alertify.class: AppVentus\AlertifyBundle\Twig\Extension\AlertifyExtension
services:
    twig.extension.alertify:
        class: %twig.extension.alertify.class%
        arguments:
            - "%av_alertify%"
        tags:
            - { name: twig.extension }
